=== hiroyasub/unitime-cregit/Documentation/Interfaces/RoomSharing.dtd
<!-- 
 * UniTime 3.5 (University Timetabling Application)
 * Copyright (C) 2014, UniTime LLC
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 -->

<!ELEMENT roomSharing ( location* ) >
<!ATTLIST roomSharing campus CDATA #REQUIRED >
<!ATTLIST roomSharing term CDATA #REQUIRED >
<!ATTLIST roomSharing year CDATA #REQUIRED >
<!ATTLIST roomSharing created CDATA #REQUIRED >

<!ELEMENT location ( department*, sharing? ) > 
<!ATTLIST location id CDATA #IMPLIED >
<!ATTLIST location building CDATA #IMPLIED >
<!ATTLIST location roomNbr CDATA #IMPLIED >
<!ATTLIST location name CDATA #IMPLIED >

<!ELEMENT department EMPTY >
<!ATTLIST department id CDATA #IMPLIED >
<!ATTLIST department code CDATA #IMPLIED >
<!ATTLIST department control (true | false) #IMPLIED >

<!ELEMENT sharing ( (unavailable | assigned)* ) >

<!ELEMENT unavailable EMPTY>
<!ATTLIST unavailable days CDATA #IMPLIED >
<!ATTLIST unavailable start CDATA #IMPLIED >
<!ATTLIST unavailable end CDATA #IMPLIED >

<!ELEMENT assigned EMPTY>
<!ATTLIST assigned days CDATA #IMPLIED >
<!ATTLIST assigned start CDATA #IMPLIED >
<!ATTLIST assigned end CDATA #IMPLIED >
<!ATTLIST assigned id CDATA #IMPLIED >
<!ATTLIST assigned code CDATA #IMPLIED >

=== hiroyasub/unitime-cregit/Documentation/Interfaces/Examples/roomSharing.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE roomSharing PUBLIC "-//UniTime//UniTime Room Sharing DTD/EN" "http://www.unitime.org/interface/RoomSharing.dtd">

<!-- 
 * UniTime 3.5 (University Timetabling Application)
 * Copyright (C) 2014, UniTime LLC
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 -->

<roomSharing campus="woebegon" year="2010" term="Fal" created="Tue Jul 29 19:37:04 CEST 2014" timeFormat="HHmm">
  <location building="EDUC" roomNbr="101" note="An example room sharing note.">
    <department code="0101"/>
    <department code="0100" control="true"/>
    <sharing>
      <!-- no start/end times: all day -->
      <!-- no days: all week -->
      <assigned code="0100"/>
      <!-- days: M for Monday, T for Tuesday, W for Wednesday, Th or R for Thursday, F for Friday, S for Saturday, Su or U for Sunday -->
      <!-- start/end: start and end time of the block -->
      <assigned days="TTh" start="1330" end="1530" code="0101"/>
      <!-- elements are processed in the given order, potentially overriding previous settings -->
      <!-- like in the above example where all times are assigned to 0100 except of TTh 1:30p - 3:30p window (which is assigned to 0101) -->
      <!-- only departments listed under the location (department elements above) can be used in sharing -->
      <!-- unavailabilities can be listed using unavailable elements  -->
      <unavailable days="SSu"/>
      <!-- all the remaining times are free for all -->
    </sharing>
  </location>
  <location building="EDUC" roomNbr="102">
    <department code="0101" control="true"/>
    <!-- an external id can be used instead of department code  -->
    <department id="D001" />
    <!-- no sharing attribute: all times are free for all -->
  </location>
  <!-- an external id can be used to identify a room or a non-university location  -->
  <location id="RM:EDC201" >
  	<department id="D001" control="true"/>
  </location>
  <location building="EDUC" roomNbr="103">
    <department code="0101" control="true"/>
  </location>
  <location building="EDUC" roomNbr="104">
    <department code="0101" control="true"/>
  </location>
  <location building="EDUC" roomNbr="105">
    <department code="0101" control="true"/>
  </location>
  <location building="EDUC" roomNbr="106">
    <department code="0101" control="true"/>
  </location>
  <location building="EDUC" roomNbr="107">
    <department code="0101" control="true"/>
  </location>
  <location building="EDUC" roomNbr="108">
    <department code="0101" control="true"/>
  </location>
  <!-- room's name can be used instead of building / roomNbr attributes -->
  <location name="THTR 101">
    <department code="0101"/>
    <department code="0100" control="true"/>
    <sharing>
      <!-- time not available -->
      <unavailable days="MTWThF" start="0730" end="1300"/>
      <!-- time assigned to a particular department -->
      <assigned days="MTWThF" start="1300" end="1530" code="0101"/>
      <assigned days="MTWThF" start="1530" end="1730" code="0100"/>
      <unavailable days="MTWThF" start="1730" end="1830"/>
    </sharing>
  </location>
  <!-- non-university locations use name instead of building / roomNbr attributes -->
  <location name="MALL">
    <department code="0102" control="true"/>
  </location>
</roomSharing>
